// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr7J13-_LVQqntTrAEdBjduWyD7piU6VY',
    appId: '1:15227413706:web:179a6f41da2b627bd84033',
    messagingSenderId: '15227413706',
    projectId: 'fitnessclubapp-dcc81',
    authDomain: 'fitnessclubapp-dcc81.firebaseapp.com',
    storageBucket: 'fitnessclubapp-dcc81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxCxk8pybsB5a6aVTkjqid6Q2y-Fwf1fQ',
    appId: '1:15227413706:android:2a2a9727b3a5a662d84033',
    messagingSenderId: '15227413706',
    projectId: 'fitnessclubapp-dcc81',
    storageBucket: 'fitnessclubapp-dcc81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcpT-tdTT_RQTbki1z49NWHnioHvnQLI',
    appId: '1:15227413706:ios:f92ae807eed33aded84033',
    messagingSenderId: '15227413706',
    projectId: 'fitnessclubapp-dcc81',
    storageBucket: 'fitnessclubapp-dcc81.firebasestorage.app',
    iosBundleId: 'com.example.fitnessClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTcpT-tdTT_RQTbki1z49NWHnioHvnQLI',
    appId: '1:15227413706:ios:f92ae807eed33aded84033',
    messagingSenderId: '15227413706',
    projectId: 'fitnessclubapp-dcc81',
    storageBucket: 'fitnessclubapp-dcc81.firebasestorage.app',
    iosBundleId: 'com.example.fitnessClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr7J13-_LVQqntTrAEdBjduWyD7piU6VY',
    appId: '1:15227413706:web:9d4837828306189cd84033',
    messagingSenderId: '15227413706',
    projectId: 'fitnessclubapp-dcc81',
    authDomain: 'fitnessclubapp-dcc81.firebaseapp.com',
    storageBucket: 'fitnessclubapp-dcc81.firebasestorage.app',
  );

}